<?php 
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

/**
 * Custom Fields
 */
class ul_ajax_requests{


	function __construct(){
		 add_action( 'wp_ajax_ul_form_submit_email',  array( $this, 'ul_form_submit_email') );
		 add_action( 'wp_ajax_nopriv_ul_form_submit_email',  array( $this, 'ul_form_submit_email') );
	}

	public function ul_form_submit_email(){
		$headers = array('Content-Type: text/html; charset=UTF-8');
		$to = 'charlestsmith888@gmail.com';
		$subject = "My off plan Form Data";
		$message = '<html><body>';
		$message .= '<table rules="all" style="border-color: #666;" cellpadding="10">';
		$message = '<html><body>';
		$message .= '<table rules="all" style="border-color: #666;" cellpadding="10">';
		foreach ($_POST as $key => $value) {
			$message .= "<tr style='background: #eee;'><td><strong>".ucwords(str_replace('_', ' ', $key)).":</strong> </td><td>".$value."</td></tr>";
		}
		$message .= "</table>";
		$message .= "</body></html>";
		$message .= "</table>";
		$message .= "</body></html>";
		wp_mail($to, $subject,$message, $headers);
		print(json_encode(array('status' => true)));
		exit();
	}


}


new ul_ajax_requests();
