<?php 
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

/**
 * Custom Fields
 */
class Ul_custom_fields{

	function __construct(){
		 
		 add_action( 'add_meta_boxes',  array( $this, 'price_section_add_meta_box') );
		 add_action( 'save_post', array( $this, 'price_section_save') );
	}


	public function price_section_get_meta($value){
		global $post;
		$field = get_post_meta( $post->ID, $value, true );
		if ( ! empty( $field ) ) {
			return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
		} else {
			return false;
		}
	}
	public function price_section_add_meta_box() {
		add_meta_box(
			'price_section-price-section1',
			__( 'Price Section', 'price_section' ),
			array( $this, 'price_section_html'),
			'property',
			'side',
			'high'
		);
		add_meta_box(
			'price_section-price-section2',
			__( 'Installment Plan Fields', 'price_section' ),
			array( $this, 'price_section_html_installment'),
			'property',
			'advanced',
			'high'
		);

		add_meta_box(
			'check_featured',
			__( 'Featured Property', 'Check_if_the_property_is_featured' ),
			array( $this, 'is_featured'),
			'property',
			'advanced',
			'high'
		);

		add_meta_box(
			'check_sold',
			__( 'Property Sold', 'Check_if_the_property_has_been_sold'),
			array( $this, 'is_sold'),
			'property',
			'advanced',
			'high'
		);
	}

	public function is_sold( $post) {
	wp_nonce_field( '_price_section_nonce', 'price_section_nonce' ); ?>
		<p>
		<label for="cs_price"><?php _e( 'Check if the property has been sold', 'Check_if_the_property_has_been_sold' ); ?></label><br>
		<input type="checkbox" name="is_sold_field" value="1" <?php echo (!empty($this->price_section_get_meta( 'is_sold_field' ))) ? 'checked' : '' ; ?>>
		</p>
		<?php
	}



	public function is_featured( $post) {
		wp_nonce_field( '_price_section_nonce', 'price_section_nonce' ); ?>
			<p>
			<label for="cs_price"><?php _e( 'Check if the property is featured', 'Check_if_the_property_is_featured' ); ?></label><br>
			<input type="checkbox" name="is_featured_field" value="1" <?php echo (!empty($this->price_section_get_meta( 'is_featured_field' ))) ? 'checked' : '' ; ?>>
			</p>
			<?php
		}



	public function price_section_html( $post) {
		wp_nonce_field( '_price_section_nonce', 'price_section_nonce' ); ?>
			<p>
			<label for="cs_price"><?php _e( 'Price', 'price_section' ); ?></label><br>
			<input type="text" name="cs_price" value="<?php echo $this->price_section_get_meta( 'cs_price' ); ?>">
			</p>

			<p>
			<label for="cs_price"><?php _e( 'Price Per Sqft from', 'price_section' ); ?></label><br>
			<input type="text" name="Price_Per_Sqft" value="<?php echo $this->price_section_get_meta( 'Price_Per_Sqft' ); ?>">
			</p>			

			<p>
			<label for="cs_price"><?php _e( 'Area from', 'price_section' ); ?></label><br>
			<input type="text" name="Area_from" value="<?php echo $this->price_section_get_meta( 'Area_from' ); ?>">
			</p>
			<?php
		}

	public function price_section_html_installment($post){
		global $post;
		$field = get_post_meta( $post->ID, 'pro_payment_schedule', true );

		$property_pdf = get_post_meta( $post->ID, 'property_pdf', true );
		$property_attachment = get_post_meta( $post->ID, 'property_attachment', true );
		$property_videoembeded = get_post_meta( $post->ID, 'property_videoembeded', true );

		?>

			
		<label for="">Upload Pdf:</label> <?php if (!empty($property_pdf)): ?><a target="_blank" href="<?= wp_get_attachment_url( $property_pdf);  ?>">View Pdf</a><?php endif; ?>
		<button type="button" class="choosebtn">Choose a file</button>
		<input type="hidden" name="property_pdf" value="<?php echo (!empty($property_pdf)) ? $property_pdf : '';  ?>">
		<div class="clearfix"></div>
		<br>


		<label for="">Upload Pdf:</label> <?php if (!empty($property_attachment)): ?><a target="_blank" href="<?= wp_get_attachment_url( $property_attachment);  ?>">View Attachment</a><?php endif; ?>
		<button type="button" class="choosebtn">Choose a file</button>
		<input type="hidden" name="property_attachment" value="<?php echo (!empty($property_attachment)) ? $property_attachment : '';  ?>">

		<div class="clearfix"></div>
		<br>
		


		<table class="appendhere">
			<tr>
				<th>Milestone</th>
				<th>Payment (%)</th>
				<th></th>
			</tr>
	
			<?php 
			$field = get_post_meta( $post->ID, 'pro_payment_schedule' , true); $field = json_decode($field);
			if (!empty($field)):  ?>
			<?php foreach ($field as $key): ?>
					<tr>
						<td><input type="text" name="Milestone[]" style="width: 100%" value="<?php echo $key[0]; ?>"></td>
						<td><input type="text" name="Payment[]" style="width: 100%" value="<?php echo $key[1]; ?>"></td>
						<td><button id="adddd">+</button><button id="delete">-</button></td>
					</tr>
				<?php endforeach ?>
				<?php else: ?>
					<tr>
						<td><input type="text" name="Milestone[]" style="width: 100%"></td>
						<td><input type="text" name="Payment[]" style="width: 100%"></td>
						<td><button id="adddd">+</button></td>
					</tr>
				<?php endif; ?>

		</table>
	

		<label for="">Video Embeded Code :</label>
		<div class="clearfix"></div>
		<textarea name="property_videoembeded" cols="200" rows="7"><?= (!empty($property_videoembeded)) ? $property_videoembeded : ''; ?></textarea>





		<script>




  jQuery(document).on('click', '.choosebtn', function( event ){
    event.preventDefault();

    var seletor_inpt = jQuery(this).next();
    // var parent = jQuery(this).parent().parent('div.field_row');
    // var inputField = jQuery(parent).find("input.meta_image_url");

  // Create a new media frame
  frame = wp.media({
    title: 'Select or Upload Media for Gallery',
    button: {
      text: 'Use this media'
    },
  multiple: false  // Set to true to allow multiple files to be selected
});


// When an image is selected in the media frame...
frame.on( 'select', function() {

// Get media attachment details from the frame state
var attachment = frame.state().get('selection').first().toJSON();

// attachment.id; //89
// attachment.title; //osts57yu7em91yaeazvq
// attachment.filename; //osts57yu7em91yaeazvq.jpg
// attachment.url; //http://localhost/testwp/wp-content/uploads/2017/09/osts57yu7em91yaeazvq.jpg
// attachment.link; //http://localhost/testwp/obituary/obituary-for-dorothy-ann-leslie/osts57yu7em91yaeazvq/
seletor_inpt.val(attachment.id);
// jQuery(parent).find("div.image_wrap").html('<img src="'+attachment.url+'" height="48" width="48" />');
});

// Finally, open the modal on click
frame.open();
});

//refrence link
//https://codex.wordpress.org/Javascript_Reference/wp.media









			jQuery(document).on('click', '#adddd', function(event) {
				event.preventDefault();
				jQuery('.appendhere').append('<tr><td><input type="text" name="Milestone[]" style="width: 100%"></td><td><input type="text" name="Payment[]" style="width: 100%"></td><td><button id="adddd">+</button><button id="delete">-</button></td></tr>');
			});
			jQuery(document).on('click', '#delete', function(event) {
				event.preventDefault();
				jQuery(this).closest('tr').remove();
			});
		</script>
	<?php }

	public	function price_section_save( $post_id ) {
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
		// if ( ! isset( $_POST['price_section_nonce'] ) || ! wp_verify_nonce( $_POST['price_section_nonce'], '_price_section_nonce' ) ) return;
		if ( ! current_user_can( 'edit_post', $post_id ) ) return;

		if ( isset( $_POST['cs_price'] ) )
			update_post_meta( $post_id, 'cs_price', esc_attr( $_POST['cs_price'] ) );
		if ( isset( $_POST['Price_Per_Sqft'] ) )
			update_post_meta( $post_id, 'Price_Per_Sqft', esc_attr( $_POST['Price_Per_Sqft'] ) );
		if ( isset( $_POST['Area_from'] ) )
			update_post_meta( $post_id, 'Area_from', esc_attr( $_POST['Area_from'] ) );
		
		if (!empty($_POST['is_featured_field'])) {
			update_post_meta( $post_id, 'is_featured_field', esc_attr( $_POST['is_featured_field'] ) );
		} else {
			delete_post_meta( $post_id, 'is_featured_field');
		}

		if (!empty($_POST['is_sold_field'])) {
			update_post_meta( $post_id, 'is_sold_field', esc_attr( $_POST['is_sold_field'] ) );
		} else {
			delete_post_meta( $post_id, 'is_sold_field');
		}

		if ( isset( $_POST['property_pdf'] ) )
			update_post_meta( $post_id, 'property_pdf', esc_attr( $_POST['property_pdf'] ) );
		if ( isset( $_POST['property_attachment'] ) )
			update_post_meta( $post_id, 'property_attachment', esc_attr( $_POST['property_attachment'] ) );
		if ( isset( $_POST['property_videoembeded'] ) )
			update_post_meta( $post_id, 'property_videoembeded', esc_attr( $_POST['property_videoembeded'] ) );
		



		if (isset($_POST['Milestone']))
			foreach ($_POST['Milestone'] as $key => $value){
				$data[$key][0] = $_POST['Milestone'][$key];	
				$data[$key][1] = $_POST['Payment'][$key]; 
			}
		update_post_meta( $post_id, 'pro_payment_schedule', json_encode($data) );
	}



}
$ul_fields = new Ul_custom_fields();
